/****************************************************
 * This file is generated by cmake.  Modify the top
 * level CMakeLists.txt to change the VERSION numbers
 ****************************************************/

#define VERSION_MAJOR 3
#define VERSION_MINOR 2
#define VERSION_PATCH 1
#define TLSH_HASH "compact hash"
#define TLSH_CHECKSUM "1 byte checksum"
